CREATE TABLE PILOT(
    ID INT PRIMARY KEY,
    NOM VARCHAR (10),
    LLINATGE VARCHAR (20),
    ÀLIES VARCHAR (20),
    NOMBRE_ACTUAL VARCHAR (20),
    PAIS VARCHAR (20),
    FOREIGN KEY (PAIS) REFERENCES PAIS(NOM_PAIS)
);

CREATE TABLE PAIS(
    NOM_PAIS VARCHAR (20)
);

CREATE TABLE EQUIPO(
    ID INT PRIMARY KEY,
    NOM_EQUIP VARCHAR (20),
    CAP_EQUIP VARCHAR (20),
    MARCA VARCHAR (20),
    FOREIGN KEY (MARCA) REFERENCES MARCA(NOM_MARCA)


);

CREATE TABLE MARCA(
    NOM_MARCA VARCHAR (20)
);

CREATE TABLE RESULTADO(

);

CREATE TABLE GRAN_PREMIO(

);
CREATE TABLE CIRCUITO(
    
);

CREATE TABLE PILOTO_EQUIPO(

);